Feat/new features
aptomx/drako pull request #7
Opened 2024-01-04 18:00 UTC by martin9718

2024-01-05 17:32 UTC, MiguelCovarrubiasdaiz approved these changes

2024-01-08 18:28 UTC, cristiancruz requested changes
Veo que se cambio el formato establecido de retornar comandos en update y create a interfaces . Esto por que fue ?

2024-01-08 18:28 UTC, cristiancruz commented on src/modules/auth/domain/services/auth.service.ts
> +  async signTokenToRecoverPassword(user: UserModel): Promise<string> {
si se remueve el await del generar token entonces también seria remover el async de la función principal.

2024-01-08 18:28 UTC, cristiancruz commented on src/modules/auth/domain/repositories/auth.interface.ts
> -  createRecoveryCode(data: RecoveryCodeModel): Promise<RecoveryCodeModel>;
Es importante mantener la estructura. crear y actualizar regresar comandos y en los demás retornar interfaces

2024-01-08 18:28 UTC, cristiancruz commented on src/modules/auth/infrastructure/repositories/auth.repository.ts
> +      where: { code, type },
también es importante validar que el email pertenezca al código y al tipo

2024-01-08 18:28 UTC, cristiancruz commented on src/modules/database/database.module.ts
> +    SequelizeModule.forRootAsync({ useClass: DatabaseService }),
habrá que respetar el nombre del servicio a un SequelizeService, por si luego se requiriera añadir otro tipo de conexión, poder identificar rápidamente a cual pertenece

2024-01-08 18:28 UTC, cristiancruz commented on src/modules/database/database.service.ts
> +      synchronize: true,
No se si funcione similar a typeOrm pero en este al estar en true si se modificaba un modelo actualizaba la db. Esto es un riesgo para producción. Seria corroborar

2024-01-08 18:59 UTC, martin9718 commented on src/modules/auth/infrastructure/repositories/auth.repository.ts
> +      where: { code, type },
Eso lo hace en la linea 45

2024-01-08 22:59 UTC, merged